config/routes.rb
Rails.application.routes.draw do
  devise_for :owners
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :mblog do
    resources :mphoto
  end
  
  root "mblog#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/mblog.rb
class Mblog < ApplicationRecord
  belongs_to :owner

  has_many_attached :photos

  
  
end

app/models/mphoto.rb
class Mphoto < ApplicationRecord
  belongs_to :mblog
  # has_one_attached :image

end

app/models/owner.rb
class Owner < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    
    has_many :mblog , dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/mblog_controller.rb
class MblogController < ApplicationController
    before_action :authenticate_owner!

    before_action :set_blog, only: [:edit,:update,:destroy]

    
    def index
            @blog= Mblog.all
            
    end


    def new
        @blog = Mblog.new
        # @photo = @blog.photos.new

    end

    def create
        @blog = current_owner.mblog.build(blog_params)
        # @photo = @blog.photos.new(photo_params)
        
        if @blog.save
            redirect_to mblog_index_path, notice:'blog was sucessfully created'
        else
            render:new
        end
    end


    def edit
        # redirect_to edit_mblog_path, notice:'blog was sucessfully created'

                
    end
    def update
        # redirect_to mblog_index_path, alert: 'acess denied' unless current_owner == @blog.user
        
        if @blog.update(blog_params)
            redirect_to mblog_index_path,notice: 'blog was sucessfully updated'
        else
            render :edit
        end

    end


    def destroy
        # @blog = Bloguser.find(params[:id])
        @blog.delete
      
        redirect_to mblog_path, notice: 'Blog was successfully destroyed.'
    end

    

        private
        def set_blog
            @blog =Mblog.find(params[:id])
            # @mphotos = @blog.mphoto

            
        end
        # def set_photo
        #     @photo = @mblog.photos.find(params[:id])
        #   end
          # app/controllers/mphotos_controller.rb
          def mphoto_params
            

          params.require(:mphoto).permit(:photos [])
        end
    
        
    
        def blog_params
            params.require(:mblog).permit(:name, :title, :description, photos: [])
          end
    
            
    


end

app/controllers/mphoto_controller.rb
class MphotoController < ApplicationController

    before_action :authenticate_owner! # Assuming authentication is required
    before_action :set_mblog
    before_action :set_photo, only: [:show, :edit, :update, :destroy]
  
    def index
      @photos = @mblog.photos
    end
  
    def show
    end
  
    def new
      @photo = @mblog.photos.new
    end
  
    def create
      @photo = @mblog.photos.new(photo_params)
  
      if @photo.save
        redirect_to mblog_photo_path(@mblog, @photo), notice: 'Photo was successfully created.'
      else
        render :new
      end
    end
  
    def edit
    end
  
    def update
      if @photo.update(photo_params)
        redirect_to mblog_photo_path(@mblog, @photo), notice: 'Photo was successfully updated.'
      else
        render :edit
      end
    end
  
    def destroy
      @photo.destroy
      redirect_to mblog_photos_path(@mblog), notice: 'Photo was successfully destroyed.'
    end
  
    private
  
    def set_mblog
      @mblog = Mblog.find(params[:mblog_id])
    end
  
    def set_photo
      @photo = @mblog.photos.find(params[:id])
    end
    # app/controllers/mphotos_controller.rb
    def mphoto_params
    params.require(:mphoto).permit(:image, :other_attributes , :photos)
  end
    
    
        
    
    end
    

app/controllers/owner_controller.rb
class OwnerController < ApplicationController


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog1_helper.rb
module Blog1Helper
end

app/helpers/mblog_helper.rb
module MblogHelper
end

app/helpers/mphoto_helper.rb
module MphotoHelper
end

app/helpers/owner_helper.rb
module OwnerHelper
end

app/helpers/photo1_helper.rb
module Photo1Helper
end

app/helpers/user1_helper.rb
module User1Helper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mblog/edit.html.erb
<%# <h1>Edit Blog</h1>
<%= render 'form', blog: @blog %>
<%# <%= link_to 'Back', blogs_path %> 



<div class="add">


<h1>Update Blog</h1>


<%= form_for(@blog, url: mblog_path, local: true, method: :patch) do |f| %>
<%# <%= form_for(@blog, url: blog_path, local: true, method: :patch) do |f| %>


<%# <%= form_for @product, url: {action: :update} do |f| %> 
   <span class="labl"> <%= f.label "Enter name" %></span>
    <span class="box" ><%= f.text_field :name %></span>
    <br><br>

    <span class="box" ><%= f.label "Enter Title:" %></span>
    <span class="box" ><%= f.text_field :title %></span>
    <br><br>

    <span class="box" ><%= f.label "Enter Description:" %></span>
    <span class="box" ><%= f.text_area :description %></span>
    <br><br>

    <span class="box" ><%= f.label "Upload Photos:" %></span>
    <span class="box" ><%= f.file_field :photos , multiple: true%></span>

    


    <br><br>

    <%= f.submit 'update Blog' %> &nbsp;&nbsp;&nbsp;
    <%= link_to 'Sign Out', destroy_owner_session_path, method: :delete %>
<% end %>
</div>

app/views/mblog/index.html.erb
<div class="indx">
<center>

<span class="head">Hello , Welcome To Our  Blog Website</span>



<span class="login"><%= link_to 'Sign IN', new_owner_session_path %> </span>
<span class="logout"><%= button_to  'Sign Out', destroy_owner_session_path , method: :delete %> </span>
  



        
        
        




<br>

<div class="tble">
<h3>Blog Lists</h3>
<div class="adnew"><%= link_to 'Add New Blog', new_mblog_path %> </div>
<br><br>



    <table border="2px solid black">
      <tr>   
        <th>Sr No.</th>  
        <th>Name</th>  
        <th>Title</th>   
        <th>Description</th>  
        <th>Blog Image </th>
        <th colspan="2">Action</th>  
      </tr>

       <% @blog.each do |mblog| %>
          <tr>
            <td><%= mblog.id %></td>   
            <td><%= mblog.name %></td>   
            <td><%= mblog.title %></td>   
            <td><%= truncate(mblog.description, :length => 75) %></td>
            <td>
              <% mblog.photos.each do |photo| %>
                <%= image_tag(photo) %>
              <% end %>
              </td>
              
             <td><%= link_to "Update",  edit_mblog_path(mblog.id), :method => 'update' %></td>
            
            <td><%= button_to 'Delete', mblog_path(mblog.id), :method => 'delete', :confirm => 'Are you sure?' %></td>   
            

              
           </tr>   
      <% end %>   
      <table>

        
</center>
</div>

        
        
        

app/views/mblog/new.html.erb
    <div class="add">
<h1>New Blog</h1>

<%= form_with(model: Mblog.new, url: mblog_index_path, local: true, method: :post) do |f| %>
   <span class="labl"> <%= f.label "Enter Name:" %></span>
    <span class="box" ><%= f.text_field :name %></span>
    <br><br>

   <span class="labl"> <%= f.label "Enter Title:" %></span>
    <span class="box1"><%= f.text_field :title %></span>
    <br><br>

    <span class="labl2"><%= f.label "Enter Description:" %></span>
    <span class="box2"><%= f.text_area :description %></span>
    <br><br>

    <span class="labl3"><%= f.label "Upload Image:" %></span>

      <span class="box3"><%= f.file_field :photos, multiple: true %> </span>
      

    




    <br><br> 





    <span class="btn"><%= f.submit 'create blog' %></span> &nbsp;&nbsp;&nbsp;
    <span class="sign"><%= link_to 'Sign Out', destroy_owner_session_path, method: :delete %></span>
<% end %>

    </center>

</div>

app/views/mphoto/edit.html.erb
<!-- app/views/mphotos/edit.html.erb -->

<h1>Edit Mphoto</h1>

<%= render 'form', mphoto: @mphoto %>

<%= link_to 'Back', mphotos_path %>

app/views/mphoto/index.html.erb
<!-- app/views/mphotos/index.html.erb -->

<h1>Mphoto Index</h1>

<% @mphoto.each do |mphoto| %>
  
    <%= image_tag(mphoto.image.url) %>
    
<% end %>

<%= link_to 'New Mphoto', new_mphoto_path %>

app/views/mphoto/new.html.erb
<!-- app/views/mphotos/new.html.erb -->

<%# <h1>New Mphoto</h1>

<%= render 'form', mphoto: @mphoto %>

<%# <%= link_to 'Back', mphotos_path %> 


<!-- app/views/mphotos/_form.html.erb -->
<%= form_with(model: Bloguser.new, url: blogs_path, local: true, method: :post) do |f| %>

<%= form_with(model: Mphoto.new,url: blogs_path, local: true, method: :post) do |form| %>
  <% if mphoto.errors.any? %>
    
      <h2><%= pluralize(mphoto.errors.count, "error") %> prohibited this mphoto from being saved:</h2>

      <ul>
        <% mphoto.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :image %>
    <%= form.file_field :image %>
  </p>

  <!-- Add any other desired form fields here -->

  
    <%= form.submit %>
  
<% end %>